-- Portfolio Manager — Postgres schema DRAFT (Neon). See docs/adr/0001.
-- STATUS: prep only. Not applied anywhere. The dual-write cutover is gated on
-- Phase 1 completion (ADR 0001). This is generated by hand from the contracts
-- package today; once the contracts cover accounting/investor shapes, the goal
-- is to generate this mechanically so the DB, app, and wire types share one
-- source (no hand-maintained drift — the exact bug class the contracts package
-- exists to kill).
--
-- Design rules baked in here:
--   * Every money mutation is transactional; broker identity is UNIQUE so a
--     retried fill cannot double-book (mirrors the crash-injection tests).
--   * Ledgers are append-only; corrections are new rows, never UPDATEs.
--   * Strategy-lot ownership is first-class (agent_id on lots), enforcing
--     invariant #3 at the data layer.

-- ── Enums (mirror contracts/proposal.js + contracts/lot.js + contracts/pipeline.js)
CREATE TYPE agent_id      AS ENUM ('agent-1', 'agent-2', 'agent-3');
CREATE TYPE proposal_side AS ENUM ('BUY', 'SELL');
CREATE TYPE proposal_status AS ENUM ('Pending', 'ApprovedForBrokerReview', 'Rejected', 'Expired');
CREATE TYPE lot_status    AS ENUM ('OPEN', 'CLOSED');
CREATE TYPE intent_source AS ENUM ('scheduled-discovery', 'lab', 'alert', 'exit-signal', 'manual');
CREATE TYPE order_state   AS ENUM (
  'Approved','Reserved','Submitted','BrokerAccepted','Partial',
  'Filled','Cancelled','Rejected','Accounted','Reconciled'
);

-- ── Research intents (contracts/pipeline.js ResearchIntentSchema) ────────────
CREATE TABLE research_intents (
  id            TEXT PRIMARY KEY,
  source        intent_source NOT NULL,
  agent_id      agent_id NOT NULL,
  ticker        TEXT,                 -- null = undirected discovery
  side          proposal_side,        -- null = undirected
  reason        TEXT NOT NULL,
  evidence_refs TEXT[] NOT NULL DEFAULT '{}',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Proposals (contracts/proposal.js ProposalSchema) ─────────────────────────
CREATE TABLE proposals (
  id                 TEXT PRIMARY KEY,
  intent_id          TEXT REFERENCES research_intents(id),
  agent_id           agent_id NOT NULL,
  ticker             TEXT NOT NULL,
  side               proposal_side NOT NULL,
  amount_dollars     NUMERIC(14,2) NOT NULL CHECK (amount_dollars > 0),
  max_price          NUMERIC(14,4) CHECK (max_price IS NULL OR max_price > 0),
  rationale          TEXT NOT NULL,
  risk_summary       TEXT NOT NULL,
  status             proposal_status NOT NULL DEFAULT 'Pending',
  -- thesis/kill-criteria (StrategyProposalSchema) — required once agents 2/3/4 land
  thesis             TEXT,
  kill_criteria      TEXT[],
  horizon_days       INTEGER,
  created_by_user_id TEXT NOT NULL,
  created_by_email   TEXT,
  decided_at         TIMESTAMPTZ,
  decided_by_user_id TEXT,
  decision_note      TEXT,
  -- HMAC over the trade-defining fields (contracts/signature.js). Signed only on approval.
  decision_hmac      TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at         TIMESTAMPTZ NOT NULL
);
CREATE INDEX proposals_status_idx ON proposals(status) WHERE status = 'Pending';

-- ── Strategy lots (contracts/lot.js StrategyLotSchema) ───────────────────────
-- agent_id is the OWNER. 'unattributed' legacy/manual lots are represented with
-- a NULL owner (an attributed strategy never owns them; invariant #3).
CREATE TABLE lots (
  lot_id          TEXT PRIMARY KEY,
  ticker          TEXT NOT NULL,
  owner_agent_id  agent_id,               -- NULL = unattributed
  open_date       DATE NOT NULL,
  cost_per_share  NUMERIC(14,4) NOT NULL CHECK (cost_per_share >= 0),
  shares_original NUMERIC(18,4) NOT NULL CHECK (shares_original > 0),
  shares_open     NUMERIC(18,4) NOT NULL CHECK (shares_open >= 0),
  status          lot_status NOT NULL DEFAULT 'OPEN',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX lots_ticker_owner_open_idx ON lots(ticker, owner_agent_id) WHERE status = 'OPEN';

-- ── Orders + fills — the double-book guard lives here ────────────────────────
CREATE TABLE orders (
  id             TEXT PRIMARY KEY,        -- = proposal id (ref_id idempotency)
  proposal_id    TEXT NOT NULL REFERENCES proposals(id),
  state          order_state NOT NULL DEFAULT 'Approved',
  broker_order_id TEXT UNIQUE,            -- UNIQUE: a broker order maps to one row, ever
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (id = proposal_id)                -- OrderIntent.refId === proposalId
);

CREATE TABLE fills (
  id              BIGSERIAL PRIMARY KEY,
  order_id        TEXT NOT NULL REFERENCES orders(id),
  broker_order_id TEXT NOT NULL,
  ticker          TEXT NOT NULL,
  side            proposal_side NOT NULL,
  shares          NUMERIC(18,4) NOT NULL CHECK (shares > 0),
  price           NUMERIC(14,4) NOT NULL CHECK (price >= 0),
  amount          NUMERIC(16,2) NOT NULL,
  agent_id        agent_id,
  realized_gain   NUMERIC(16,2),          -- SELL only
  filled_at       TIMESTAMPTZ NOT NULL,
  -- A given broker order is accounted exactly once — the crash-replay guarantee
  -- the fill-processing tests assert, enforced by the database.
  UNIQUE (broker_order_id)
);

-- Which lots a SELL fill consumed (contracts/lot.js LotConsumptionSchema).
-- Append-only; attributes realized P&L to the consumed owned lots.
CREATE TABLE lot_consumptions (
  id                BIGSERIAL PRIMARY KEY,
  fill_id           BIGINT NOT NULL REFERENCES fills(id),
  lot_id            TEXT NOT NULL REFERENCES lots(lot_id),
  shares_consumed   NUMERIC(18,4) NOT NULL CHECK (shares_consumed > 0),
  cost_per_share    NUMERIC(14,4) NOT NULL,
  proceeds_per_share NUMERIC(14,4) NOT NULL,
  gain              NUMERIC(16,2) NOT NULL,
  owner_agent_id    agent_id,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── Operational (partly exists in Redis/Sheets today) ────────────────────────
CREATE TABLE job_runs (
  id         BIGSERIAL PRIMARY KEY,
  job        TEXT NOT NULL,
  status     TEXT NOT NULL,           -- ok | failed | degraded (budget_exhausted/scan_error)
  started_at TIMESTAMPTZ NOT NULL,
  ended_at   TIMESTAMPTZ,
  detail     JSONB
);
CREATE INDEX job_runs_job_time_idx ON job_runs(job, started_at DESC);

CREATE TABLE audit_events (
  id         BIGSERIAL PRIMARY KEY,
  action     TEXT NOT NULL,
  actor      TEXT,
  target     TEXT,
  payload    JSONB,
  hmac       TEXT,                     -- append-only signed ledger row
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ── TODO — need contracts first, then add here ───────────────────────────────
--   accounts, investors, capital_entries (double-entry cash/units event ledger),
--   positions (broker-reconciled), snapshots (point-in-time NAV), evidence,
--   risk_snapshots. These carry the NAV/units math; drafting them before their
--   Zod contracts exist would just re-create the drift the contracts package
--   removes, so they wait for the accounting-contract slice.
